name: "os_phone_book"
human_name: "O.S. Phonebook"
user: "phone_book"
unicorn_socket: "tmp/sockets/unicorn.sock"
secret_token_file: "config/secret/token"
deploy_user: "deploy"
database: "sqlite3"
repository: "git://github.com/OSSystems/OSPhoneBook.git"
short_description: "Phonebook system."
description: "Phonebook system with Asterisk server integration."
use_nginx: true
